behaviors:
  Kart:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 10240
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000
    time_horizon: 64
    summary_freq: 2000
